class MovieList {
  String backdropPath;
  int id;
  String originalTitle;
  String overview;
  String posterPath;
  String releaseDate;
  String title;
  double voteAverage;
  bool isFavorite;

  MovieList({
    required this.backdropPath,
    required this.id,
    required this.originalTitle,
    required this.overview,
    required this.posterPath,
    required this.releaseDate,
    required this.title,
    required this.voteAverage,
    this.isFavorite = false,
  });
}

var baseUrl = "https://image.tmdb.org/t/p/w500";

var moviePlayList = [
  MovieList(
      backdropPath: "/2klQ1z1fcHGgQPevbEQdkCnzyuS.jpg",
      id: 502356,
      originalTitle: "The Super Mario Bros. Movie",
      overview: "While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.",
      posterPath: "/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
      releaseDate: "2023-04-05",
      title: "The Super Mario Bros. Movie",
      voteAverage: 7.8
  ),
  MovieList(
    backdropPath: "/4t0oBFrJyweYPt0hocW6RUa0b6H.jpg",
    id: 385687,
    originalTitle: "Fast X",
    overview: "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
    posterPath: "/1E5baAaEse26fej7uHcjOgEE2t2.jpg",
    releaseDate: "2023-05-17",
    title: "Fast X",
    voteAverage: 7.1
  ),
  MovieList(
      backdropPath: "/1IM8i8HiomFC4y6NRyBuDrHJWg3.jpg",
      id: 447277,
      originalTitle: "The Little Mermaid",
      overview: "The youngest of King Triton’s daughters, and the most defiant, Ariel longs to find out more about the world beyond the sea, and while visiting the surface, falls for the dashing Prince Eric. With mermaids forbidden to interact with humans, Ariel makes a deal with the evil sea witch, Ursula, which gives her a chance to experience life on land, but ultimately places her life – and her father’s crown – in jeopardy.",
      posterPath: "/ym1dxyOk4jFcSl4Q2zmRrA5BEEN.jpg",
      releaseDate: "2023-05-18",
      title: "The Little Mermaid",
      voteAverage: 6.1
  ),
  MovieList(
      backdropPath: "/nyZ8e7lRRwdF21NyydRIo0B9AXZ.jpg",
      id: 840326,
      originalTitle: "Sisu",
      overview: "Deep in the wilderness of Lapland, Aatami Korpi is searching for gold but after he stumbles upon Nazi patrol, a breathtaking and gold-hungry chase through the destroyed and mined Lapland wilderness begins.",
      posterPath: "/ygO9lowFMXWymATCrhoQXd6gCEh.jpg",
      releaseDate: "2022-10-12",
      title: "Sisu",
      voteAverage: 7.5,
  ),
  MovieList(
      backdropPath: "/aAgGrfBwna1nO4M2USxwFgK5O0t.jpg",
      id: 713704,
      originalTitle: "Evil Dead Rise",
      overview: "Three siblings find an ancient vinyl that gives birth to bloodthirsty demons that run amok in a Los Angeles apartment building and thrusts them into a primal battle for survival as they face the most nightmarish version of family imaginable.",
      posterPath: "/5ik4ATKmNtmJU6AYD0bLm56BCVM.jpg",
      releaseDate: "2023-04-12",
      title: "Evil Dead Rise",
      voteAverage: 7.1,
  ),
  MovieList(
      backdropPath: "/T5xXoFqyc9jNXZIbH4Sw0jwWjw.jpg",
      id: 605886,
      originalTitle: "To Catch a Killer",
      overview: "Baltimore. New Year's Eve. A talented but troubled police officer is recruited by the FBI's chief investigator to help profile and track down a mass murderer.",
      posterPath: "/mFp3l4lZg1NSEsyxKrdi0rNK8r1.jpg",
      releaseDate: "2023-04-06",
      title: "To Catch a Killer",
      voteAverage: 7.0,
  ),
  MovieList(
      backdropPath: "/kyeqDT2cFhTmwlvtuQY3n2W6Vf3.jpg",
      id: 799379,
      originalTitle: "늑대사냥",
      overview: "While under heavily armed guard, the dangerous convicts aboard a cargo ship unite in a coordinated escape attempt that soon escalates into a bloody, all-out riot. But as the fugitives continue their brutal campaign of terror, they soon discover that not even the most vicious among them is safe from the horror they unknowingly unleashed from the darkness below deck.",
      posterPath: "/dniWicB6fa7NvpGbguxWlNPMc5f.jpg",
      releaseDate: "2022-09-21",
      title: "Project Wolf Hunting",
      voteAverage: 6.5,
  ),
  MovieList(
    backdropPath: "/51vreLbrGwzAg4WRCHgitWz6Naw.jpg",
    id: 447365,
    originalTitle: "Guardians of the Galaxy Vol. 3",
    overview: "Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.",
    posterPath: "/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
    releaseDate: "2022-09-21",
    title: "Guardians of the Galaxy Vol. 3",
    voteAverage: 8.1,
  ),
  MovieList(
    backdropPath: "/hiHGRbyTcbZoLsYYkO4QiCLYe34.jpg",
    id: 758323,
    originalTitle: "The Pope's Exorcist",
    overview: "Father Gabriele Amorth, Chief Exorcist of the Vatican, investigates a young boy's terrifying possession and ends up uncovering a centuries-old conspiracy the Vatican has desperately tried to keep hidden.",
    posterPath: "/4IjRR2OW2itjQWQnmlUzvwLz9DQ.jpg",
    releaseDate: "2023-04-05",
    title: "The Pope's Exorcist",
    voteAverage: 7.3,
  ),
  MovieList(
    backdropPath: "/i1eghEBiC0gN4KnwuUGC2fNiX1f.jpg",
    id: 552688,
    originalTitle: "The Mother",
    overview: "A deadly female assassin comes out of hiding to protect the daughter that she gave up years before, while on the run from dangerous men.",
    posterPath: "/vnRthEZz16Q9VWcP5homkHxyHoy.jpg",
    releaseDate: "2023-05-04",
    title: "The Mother",
    voteAverage: 6.8,
  ),
  MovieList(
    backdropPath: "/eTvN54pd83TrSEOz6wbsXEJktCV.jpg",
    id: 882569,
    originalTitle: "Guy Ritchie's The Covenant",
    overview: "During the war in Afghanistan, a local interpreter risks his own life to carry an injured sergeant across miles of grueling terrain.",
    posterPath: "/jZy73aPYrwwhuc37ALgnJUCaTnK.jpg",
    releaseDate: "2023-04-19",
    title: "Guy Ritchie's The Covenant",
    voteAverage: 7.5,
  ),
  MovieList(
      backdropPath: "/2I5eBh98Q4aPq8WdQrHdTC8ARhY.jpg",
      id: 569094,
      originalTitle: "Spider-Man: Across the Spider-Verse",
      overview: "After reuniting with Gwen Stacy, Miles Morales — Brooklyn's full-time, friendly neighborhood Spider-Man — is catapulted across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must redefine what it means to be a hero so he can save the people he loves most.",
      posterPath: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
      releaseDate: "2023-05-31",
      title: "Spider-Man: Across the Spider-Verse",
      voteAverage: 8.0,
  ),
  MovieList(
      backdropPath: "/qElNES0sHVQcbzvGrTx7ccpGzij.jpg",
      id: 842675,
      originalTitle: "流浪地球2",
      overview: "A prequel to The Wandering Earth.",
      posterPath: "/pR858ihc6Ls9xohpdRJVjV787ml.jpg",
      releaseDate: "2023-01-22",
      title: "The Wandering Earth II",
      voteAverage: 7.2,
  ),
  MovieList(
    backdropPath: "/qElNES0sHVQcbzvGrTx7ccpGzij.jpg",
    id: 842675,
    originalTitle: "流浪地球2",
    overview: "A prequel to The Wandering Earth.",
    posterPath: "/pR858ihc6Ls9xohpdRJVjV787ml.jpg",
    releaseDate: "2023-01-22",
    title: "The Wandering Earth II",
    voteAverage: 7.2,
  ),
  MovieList(
    backdropPath: "/wIb43RlPf5iYeoBAYIfxfhpE8NI.jpg",
    id: 1094319,
    originalTitle: "The Best Man",
    overview: "Mercenaries seize control of a remote resort hotel during a wedding and it's up to the best man, the groom and their drunken best friend to stop the terrorists and save the hostages.",
    posterPath: "/c9f6mFZqkyz4AD0sxGmynE1pe0v.jpg",
    releaseDate: "2023-04-21",
    title: "The Best Man",
    voteAverage: 6.0
  ),
  MovieList(
      backdropPath: "/44immBwzhDVyjn87b3x3l9mlhAD.jpg",
      id: 934433,
      originalTitle: "Scream VI",
      overview: "Following the latest Ghostface killings, the four survivors leave Woodsboro behind and start a fresh chapter.",
      posterPath: "/wDWwtvkRRlgTiUr6TyLSMX8FCuZ.jpg",
      releaseDate: "2023-03-08",
      title: "Scream VI",
      voteAverage: 7.3,
  ),
  MovieList(
    backdropPath: "/9qcXIX4Sjv6oEKLvaLYJTabLqR.jpg",
    id: 1020696,
    originalTitle: "Play Dead",
    overview: "Criminology student Chloe fakes her own death to break into a morgue, in order to retrieve a piece of evidence that ties her younger brother to a crime gone wrong. Once inside, she discovers that a sadistic coroner is using the corpses for his sick and twisted business, and when he realises that Chloe still has a pulse, a terrifying game of cat and mouse ensues.",
    posterPath: "/doRkaLpyvmKHEFBe5Oc1wPE7EdX.jpg",
    releaseDate: "2022-12-09",
    title: "Play Dead",
    voteAverage: 6.8,
  ),
  MovieList(
    backdropPath: "/oblUNeHlwV3VsjB5ITMlco5ZSOF.jpg",
    id: 493529,
    originalTitle: "Dungeons & Dragons: Honor Among Thieves",
    overview: "A charming thief and a band of unlikely adventurers undertake an epic heist to retrieve a lost relic, but things go dangerously awry when they run afoul of the wrong people.",
    posterPath: "/A7AoNT06aRAc4SV89Dwxj3EYAgC.jpg",
    releaseDate: "2023-03-23",
    title: "Dungeons & Dragons: Honor Among Thieves",
    voteAverage: 7.5,
  ),
  MovieList(
    backdropPath: "/ceYZCBfwbBwSpGJ6PapNVw5jqLG.jpg",
    id: 916224,
    originalTitle: "すずめの戸締まり",
    overview: "Suzume, 17, lost her mother as a little girl. On her way to school, she meets a mysterious young man. But her curiosity unleashes a calamity that endangers the entire population of Japan, and so Suzume embarks on a journey to set things right.",
    posterPath: "/vIeu8WysZrTSFb2uhPViKjX9EcC.jpg",
    releaseDate: "2022-11-11",
    title: "Suzume",
    voteAverage: 7.9,
  ),
  MovieList(
    backdropPath: "/qAfGVKCOg1ueNFOA9KL85lo9zox.jpg",
    id: 1016121,
    originalTitle: "Beautiful Disaster",
    overview: "Bad-boy Travis is exactly what college freshman Abby needs and wants to avoid. He spends his nights fighting in underground boxing matches, and his days as the ultimate college campus charmer. But Abby wants nothing to do with Travis. Intrigued by Abby’s resistance, Travis offers her a simple bet: if he loses his next fight, he must remain sex-free for a month. If he wins, Abby must live in his apartment for the same amount of time. Either way, Travis has no idea that Abby’s dark past is about to emerge, and he may have finally met his match.",
    posterPath: "/bwdLflvCcOCRPqb1x13KPuYIzVx.jpg",
    releaseDate:  "2023-04-04",
    title: "Beautiful Disaster",
    voteAverage: 6.1,
  ),
];